version: 0.2

environment_variables:
  plaintext:
    SRC_DIR: /static
            
phases:

  install: 
    commands:
      - echo Entered the install phase...
      - pwd
      - ls -l
      - go version
      - go get -u github.com/golang/lint/golint
      - cp /static .

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - static/*
    - config/*
    - codedeploy/*
    - cloudformation/*
