version: 0.2

environment_variables:
  plaintext:
    SRC_DIR: static
            
phases:

  install: 
    commands:
      - echo Entered the install phase...
      - go version
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Run all tests included with our application
      - go test

  build:
    commands:

      # Build our application
      - go build -o app
      - df -h
      - pwd
      - ls -l
      - mkdir -p static/stylesheets

  post_build:
    commands:
      - mkdir -p static
      - pwd
      - ls -l

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - static/*
    - config/*
    - codedeploy/*
    - cloudformation/*
